Improved script.

diff --git a/create-instance b/create-instance
--- a/create-instance
+++ b/create-instance
@@ -50,14 +50,14 @@ fi
 
 
 # ====== Obtain list of all NSDs ===========================================
-NSD_LIST=`git ls-files | cut -d/ -f1 | sort -u | grep "nsd$\\|ns$"`
+NSD_LIST=`git ls-files | cut -d/ -f1 | sort -u | grep "[_-]nsd$\\|[_-]ns$"`
 
 # ------ Obtaining a mapping between NSD directory and NSD identifier =====
 declare -A nsdIdentifierArray
 declare -A nsdArray
 declare -A nsdYamlFileArray
 for nsd in ${NSD_LIST} ; do
-   echo "$nsd:"
+   echo -en "${nsd}:\t"
    if [ -e "${nsd}/${nsd}.yaml" ] ; then
       nsdYamlName="${nsd}/${nsd}.yaml"
    elif [ -e "${nsd}/${nsd}d.yaml" ] ; then
@@ -66,16 +66,17 @@ for nsd in ${NSD_LIST} ; do
       echo >&2 "ERROR: Unable to find YAML file for ${nsd}!"
       exit 1
    fi
-   nsdIdentifier=`grep "^    id:" ${nsdYamlName} | tr -d " \t\n" | sed -e "s/id://"`
+   echo -en "(${nsdYamlName})\t"
+   nsdIdentifier=`yq -r ".nsd.nsd[].id" ${nsdYamlName}`
    if [ "${nsdIdentifier}" == "" ] ; then
-      echo >&2 "ERROR: Unable to find identifier for NSD ${nsd}!"
+      echo >&2 "ERROR: Unable to find identifier for NSD ${nsd} in ${nsdYamlName}!"
       exit 1
    fi
    nsdIdentifierArray[${nsd}]="${nsdIdentifier}"
    nsdYamlFileArray[${nsd}]="${nsdYamlName}"
    nsdArray[${nsdIdentifier}]="${nsd}"
 
-   # echo "${nsdArray[${nsdIdentifier}]} <-> ${nsdIdentifierArray[${nsd}]}"
+   echo "${nsdArray[${nsdIdentifier}]} <-> ${nsdIdentifierArray[${nsd}]}"
 done
 
 
@@ -86,7 +87,7 @@ VNFD_LIST=`git ls-files | cut -d/ -f1 | sort -u | grep "vnfd$\\|vnf$"`
 declare -A vnfdIdentifierArray
 declare -A vnfdArray
 for vnfd in ${VNFD_LIST} ; do
-   echo "$vnfd:"
+   echo -en "${vnfd}:\t"
    if [ -e "${vnfd}/${vnfd}.yaml" ] ; then
       vnfdYamlName="${vnfd}/${vnfd}.yaml"
    elif [ -e "${vnfd}/${vnfd}d.yaml" ] ; then
@@ -95,15 +96,16 @@ for vnfd in ${VNFD_LIST} ; do
       echo >&2 "ERROR: Unable to find YAML file for ${vnfd}!"
       exit 1
    fi
-   vnfdIdentifier=`grep "^  id:" ${vnfdYamlName} | tr -d " \t\n" | sed -e "s/id://"`
+   echo -en "${vnfdYamlName}\t"
+   vnfdIdentifier=`yq -r ".vnfd.id" ${vnfdYamlName}`
    if [ "${vnfdIdentifier}" == "" ] ; then
-      echo >&2 "ERROR: Unable to find identifier for VNFD ${vnfd}!"
+      echo >&2 "ERROR: Unable to find identifier for VNFD ${vnfd} in ${vnfdYamlName}!"
       exit 1
    fi
    vnfdIdentifierArray[${vnfd}]="${vnfdIdentifier}"
    vnfdArray[${vnfdIdentifier}]="${vnfd}"
 
-   # echo "${vnfdArray[${vnfdIdentifier}]} <-> ${vnfdIdentifierArray[${vnfd}]}"
+   echo "${vnfdArray[${vnfdIdentifier}]} <-> ${vnfdIdentifierArray[${vnfd}]}"
 done
 
 
@@ -127,7 +129,7 @@ while [ $# -gt 0 ] ; do
    fi
    nsd="${nsdArray[${nsdIdentifier}]}"
    if [ "$nsd" == "" ] ; then
-      echo >&2 "ERROR: Unable to find for NSD for identifier ${nsdIdentifier}!"
+      echo >&2 "ERROR: Unable to find NSD for identifier ${nsdIdentifier} in ( ${!nsdArray[@]} )!"
       exit 1
    fi
    nsdYamlFileName="${nsdYamlFileArray[${nsd}]}"
@@ -165,7 +167,7 @@ while [ $# -gt 0 ] ; do
    for vnfdIdentifier in ${vnfdIdentifierList} ; do
       vnfd="${vnfdArray[${vnfdIdentifier}]}"
       if [ "${vnfd}" == "" ] ; then
-         echo >&2 "ERROR: Unable to find for VNFD for identifier ${vnfdIdentifier}!"
+         echo >&2 "ERROR: Unable to find VNFD for identifier ${vnfdIdentifier} in ( ${!vnfdArray[@]} )!"
          exit 1
       fi
       vnfdTarball="${vnfd}.tar.gz"
